package server

import "net/http"

type TompModule int

const (
	OperatorInformation TompModule = 1
	Planning            TompModule = 2
	Booking             TompModule = 3
	TripExecution       TompModule = 4
	Support             TompModule = 5
	Payment             TompModule = 6
	General             TompModule = 7
	CustomerManagement  TompModule = 8
)

type SubCode int

const (

	/**
	**/
	Missing SubCode = iota + 1
	Invalid
	IllegalOperation
	TechnicalIssue
	NoAccessToEndpoint
)

type ErrorCode int

func NewErrorCode(module TompModule) ErrorCode {
	return 0
}

type TompError struct {
	// The TOMP specific error code.
	// See https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP for more details of this error.
	Errorcode *int32 `json:"errorcode,omitempty"`
	// The category of this type of error.
	Type *string `json:"type,omitempty"`
	// A short, human-readable summary of the problem type.  It SHOULD NOT
	// change from occurrence to occurrence of the problem, except to match Content-Language
	Title *string `json:"title,omitempty"`
	// The HTTP status code ([RFC7231], Section 6) generated by the origin
	// server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem,
	//could match Content-Language
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`
}

func httpError(w http.ResponseWriter) {

}
